name: hybrid_logical_clocks
description: An implementation of HLC from the original paper without 
  dependencies
version: 1.0.1
repository: https://github.com/dodgog/hybrid-logical-clocks-dart

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
